services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    expose:
      - "443"
    networks:
      - network

  suricata:
    build:
      dockerfile: Dockerfile
    container_name: suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    ports:
      - "443:443"
    entrypoint: ./startup.sh
    depends_on:
      - nginx
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./suricata/config:/etc/suricata
      - ./suricata/rules:/var/lib/suricata/rules
      - ./startup.sh:/startup.sh
    networks:
      - network

networks:
  network:
    driver: bridge
